default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: telegram_dms_development
  username: telegram_dms
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: telegram_dms_test

production:
  <<: *default
  database: telegram_dms_production
  username: telegram_dms
  password: <%= ENV['TELEGRAM_DMS_DATABASE_PASSWORD'] %>
